### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [adanghidayat/SEBC#1]
Please be sure to configure your Issues and Milestones according to the README.

Also please add @jamestyj as a Collaborator.

**Comment by adanghidayat** [comment]
already add @jamestyj, waiting for confirmation

**Comment by mfernest** [comment]
Please modify your Issues, Labels, and Milestones when you get a moment.

**Comment by adanghidayat** [comment]
ok, sorry for late response
